name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer Action
      uses: ArtemisSkat/buildozer-action@v1.2
      with:
        command: buildozer -v android debug
        repository_root: .

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: JARVIS-APK
        path: bin/*.apk
